const { Events } = require('discord.js');

module.exports = {
	name: Events.ClientReady,
	once: true,
	async execute(client) {
		console.log(`^2Ready! ^1Logged in as: ^0${client.user.tag}`);

		const serverGuild = await client.guilds.cache.get(client.config.General.serverID);
		const guildChannel = await client.channels.cache.get(client.config.DiscordBot.PlayerStatus.channelID);
		const guildStatusChannel = await client.channels.cache.get(client.config.DiscordBot.PlayerStatus.channelCountID);

		await guildChannel.bulkDelete(1)
		let statusEmbed = new client.discord.EmbedBuilder()
			.setColor(0x0099FF)
			.setTitle(`${client.config.DiscordBot.PlayerStatus.embedConfig.title}`)
			.setURL(`${client.config.DiscordBot.PlayerStatus.embedConfig.url}`)
			.setAuthor({ name: `${client.user.username}`, iconURL: `${client.user.displayAvatarURL()}`, url: 'https://conceptcollective.net' })
			.setDescription('Server has been started ✅')
			.setThumbnail(`${client.config.DiscordBot.PlayerStatus.embedConfig.thumbnail}`)
			.setTimestamp()
			.setFooter({ text: 'This message was generated by ccDiscordWrapper', iconURL: 'https://conceptcollective.net/img/icon.png', URL: 'https://conceptcollective.net' });
		let playerCountNum = 0;

		if (client.config.DiscordBot.PlayerStatus.channelCountID !== false){
			updateChannelName(playerCountNum)
		}
		let playerCount = [];
		let players = '**Currently Connected Player(s)**:\n';
		let nameString = '';
		await guildChannel.bulkDelete(1).catch(e => console.warn('Failed to delete previous message - probably becuase there isn\'t one!'));
		await guildChannel.send({embeds: [statusEmbed]}).then(async sentMessage => {
			client.statusMessage = await sentMessage;
		});
		
		on('playerJoining', async (source) => {
			if (client.config.DiscordBot.enabled === true) {
				let playerDiscordID = GetPlayerIdentifierByType(source, 'discord').substring(8)
				let playerName = GetPlayerName(source);
				if (playerDiscordID) {
					try {
						let discordMember = await serverGuild.members.fetch(playerDiscordID)
						client.players[playerName] = {
							id: discordMember.id,
							avatarURL: discordMember.user.avatarURL(),
							roles: discordMember.roles.cache.map(role => role),
							joinedAt: discordMember.joinedTimestamp,
							username: discordMember.user.username,
							nickname: discordMember.nickname,
							inGuild: true,
						}
					} catch (e) {
						client.players[playerName] = {
							id: playerDiscordID,
							avatarURL: null,
							roles: [{ "name": client.config.DiscordBot.PlayerRoles.notInDiscord }],
							joinedAt: null,
							username: null,
							nickname: null,
							inGuild: false,
						}
						console.warn('Failed to fetch member from Discord API - is the player in your Discord server?')
					}
				} else {
					console.warn('Unable to fetch players Discord ID from FiveM...')
					return client.players[playerName] = {
						id: null,
						avatarURL: null,
						roles: [{ "name": client.config.DiscordBot.PlayerRoles.DiscordnotFound }],
						joinedAt: null,
						username: null,
						nickname: null,
						inGuild: null,
					}
				}

				if (client.config.Debug === true) {
					console.log(`Player data: ${JSON.stringify(client.players)}`)
				}

				playerCountNum++;
				let playerActualDiscord = client.players[playerName].id

				if (client.config.DiscordBot.PlayerStatus.listPlayers === true){
					nameString = `‣ ${playerName} - <@${playerActualDiscord}>`;
					playerCount.push(nameString)
					playerCount.forEach(player => {
						players += `${player}\n`;
					})
					updatePlayerNames(players, statusEmbed)
				} if (client.config.DiscordBot.PlayerStatus.channelCountID !== false){
					updateChannelName(playerCountNum)
				} else {
					statusEmbed.setDescription(`There are currently ${playerCountNum} players connected to the server!`)
				}

				if (client.config.DiscordBot.PlayerAcePermissions.enabled === true) {
					client.config.DiscordBot.PlayerAcePermissions.roleList.forEach(role => {
						let playerCheck = doesPlayerHaveRole(role.roleID, source)
						let playerRole = client.players[playerName].roles.filter(rolef => rolef.id === role.roleID)[0]
						if (playerCheck === true) {
							console.log(`^2${playerName} ^0has the role ^3${playerRole.name} ^0- ^8adding ACE permission ^1${role.aceGroup}^0!`)
							ExecuteCommand(`add_principal identifier.discord:${playerDiscordID} ${role.aceGroup}`)
						}
					})
				}
			}
			if (client.config.DiscordRPC.enabled === true) {
				emitNet("onServerConfigLoad", source, client.config)
			}
		})
		on('playerDropped', (reason) => {
			playerCountNum--;
			let playerActualDiscord = GetPlayerIdentifierByType(source, 'discord').substring(8)
			delete client.players[playerActualDiscord];
			if (client.config.Debug === true) {
				console.log(`Player data: ${JSON.stringify(client.players)}`)
			}
			if (client.config.DiscordBot.PlayerStatus.listPlayers === true){
				nameString = `‣ ${GetPlayerName(source)} - <@${playerActualDiscord}>`;
				playerCount = playerCount.filter( e => e !== nameString);
				players = '**Currently Connected Player(s)**:\n';
				playerCount.forEach(player => {
					players += `${player}\n`;
				})
				updatePlayerNames(players, statusEmbed)
			} if (client.config.DiscordBot.PlayerStatus.channelCountID !== false){
				updateChannelName(playerCountNum)
			} else {
				statusEmbed.setDescription(`There are currently ${playerCount} players connected to the server!`)
			}
		})

		function updateChannelName(playerCountNumber){
			if (playerCountNumber === 1){
				guildStatusChannel.edit({ name: `🦲｜${playerCountNumber}-player` });
			} else {
				guildStatusChannel.edit({ name: `🦲｜${playerCountNumber}-players` });
			}
		}

		function updatePlayerNames(players, statusEmbed) {
			if (players === '**Currently Connected Player(s)**:\n'){
				statusEmbed.setDescription('**There are currently no players connected!**');
			} else {
				statusEmbed.setDescription(players);
			};
			client.statusMessage.edit({embeds: [statusEmbed]});
		}

		function doesPlayerHaveRole(roleID, source){
			let playerName = GetPlayerName(source);
			let playerRoles = client.players[playerName].roles
			let playerHasRole = false
			playerRoles.forEach(role => {
				if (role.id === roleID){
					playerHasRole = true
				}
			})
			return playerHasRole
		}

	},
};