const { Events } = require('discord.js');

module.exports = {
	name: Events.ClientReady,
	once: true,
	async execute(client) {
		console.log(`Ready! Logged in as ${client.user.tag}`);
		const guildChannel = client.channels.cache.get(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusChannelId'));
		await guildChannel.bulkDelete(2).then(message => console.log('^2Deleted previous message!'))
		// inside a command, event listener, etc.
		const statusEmbed = new client.discord.EmbedBuilder()
			.setColor(0x0099FF)
			.setTitle(`${GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedTitle')} - Status`)
			.setURL(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedURL'))
			.setAuthor({ name: 'CC-Discord-Status', iconURL: 'https://conceptcollective.net/img/icon.png', url: 'https://conceptcollective.net' })
			.setDescription('Server has been started <:checkmark:964881366099558481>')
			.setThumbnail(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedThumbnail'))
			.setTimestamp()
			.setFooter({ text: 'This message was generated by cc-discordStatus', iconURL: 'https://conceptcollective.net/img/icon.png', url: 'https://conceptcollective.net' });

		guildChannel.send({embeds: [statusEmbed]}).then(async sentMessage => {
			client.statusMessage = sentMessage
			playerCount = 0;
			if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
				playerCount = '';
			}
			on('playerConnecting', (playerName, kickReason, deferrals) => {
				if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
					playerCount += `‣ ${playerName} - <@${GetPlayerIdentifier(source, 3).substring(8)}>`
					statusEmbed.setDescription(`**Currently Connected Players**:\n\n${playerCount}`)
					console.log(playerName)
				} else {
					playerCount++;
					statusEmbed.setDescription(`There are currently ${playerCount} players connected to the server!`)
				}
				sentMessage.edit({embeds: [statusEmbed]})
			})
			on('playerDropped', (source, reason) => {
				if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
					playerCount.replace(`‣ ${playerName} - <@${GetPlayerIdentifier(source, 3).substring(8)}>`, '');
					statusEmbed.setDescription(`**Currently Connected Players**:\n\n${playerCount}`)
				} else {
					playerCount--;
					statusEmbed.setDescription(`There are currently ${playerCount} players connected to the server!`)
				}
				sentMessage.edit({embeds: [statusEmbed]})
			})
		});
	},
};