const { Events } = require('discord.js');

module.exports = {
	name: Events.ClientReady,
	once: true,
	async execute(client) {
		console.log(`Ready! Logged in as ${client.user.tag}`);
		const guildChannel = client.channels.cache.get(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusChannelId'));
		await guildChannel.bulkDelete(2).then(message => console.log('^2Deleted previous message!'))
		// inside a command, event listener, etc.
		const statusEmbed = new client.discord.EmbedBuilder()
			.setColor(0x0099FF)
			.setTitle(`${GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedTitle')} - Status`)
			.setURL(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedURL'))
			.setAuthor({ name: `${client.user.username}`, iconURL: `${client.user.displayAvatarURL()}`, url: 'https://conceptcollective.net' })
			.setDescription('Server has been started <:checkmark:964881366099558481>')
			.setThumbnail(GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusEmbedThumbnail'))
			.setTimestamp()
			.setFooter({ text: 'This message was generated by cc-discordStatus', iconURL: 'https://conceptcollective.net/img/icon.png', URL: 'https://conceptcollective.net' });

		guildChannel.send({embeds: [statusEmbed]}).then(async sentMessage => {
			client.statusMessage = sentMessage
			playerCount = 0;
			players = '';
			if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
				playerCount = [];
				nameString = '';
			}
			on('playerConnecting', (playerName, kickReason, deferrals) => {
				if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
					nameString = `‣ ${playerName} - <@${GetPlayerIdentifier(source, 3).substring(8)}>`;
					playerCount.push(nameString)
					players = '**Currently Connected Player(s)**:\n';
					playerCount.forEach(player => {
						players += `${player}\n`;
					})
					statusEmbed.setDescription(`${players}`)
				} else {
					playerCount++;
					statusEmbed.setDescription(`There are currently ${playerCount} players connected to the server!`)
				}
				sentMessage.edit({embeds: [statusEmbed]})
			})
			on('playerDropped', (reason) => {
				if (GetResourceMetadata(GetCurrentResourceName(), 'DiscordStatusPlayerNames') === 'true'){
					nameString = `‣ ${GetPlayerName(source)} - <@${GetPlayerIdentifier(source, 3).substring(8)}>`;
					playerCount = playerCount.filter( e => e !== nameString);
					players = '**Currently Connected Player(s)**:\n';
					playerCount.forEach(player => {
						players += `${player}\n`;
					})
					statusEmbed.setDescription(players)
				} else {
					playerCount--;
					statusEmbed.setDescription(`There are currently ${playerCount} players connected to the server!`)
				}
				sentMessage.edit({embeds: [statusEmbed]})
			})
		});
	},
};